- name: Config Juniper MX-480
  hosts: mx-series
  gather_facts: no
  vars:
    ansible_command_timeout: 300
  vars_files:
  - vars/main.yml
  tasks:
  - name: Config
    junipernetworks.junos.junos_config:
      src: "templates/addresses.j2"
      confirm_commit: yes
      update: merge
      comment: Config interfaces