- name: Config Juniper MX-460
  hosts: mx-460
  gather_facts: no
  vars:
    ansible_command_timeout: 300
  vars_files:
  - vars/main.yml
  tasks:
  - name: Config
    junipernetworks.junos.junos_config:
      src: "templates/config.j2"
      confirm_commit: yes
      update: merge
      comment: Config Juniper