- name: Config Juniper MX-480
  hosts: mx-series
  gather_facts: no
  vars:
    ansible_command_timeout: 300
  vars_files:
    - vars/ebgp.yml
    - vars/vni.yml
  tasks:
    # - name: Config eBGP Overlay
    #   junipernetworks.junos.junos_config:
    #     src: "templates/ebgp.j2"
    #     confirm_commit: yes
    #     update: merge
    # #     comment: Config eBGP Overlay
    # - name: Config Layer 3 VNIs
    #   junipernetworks.junos.junos_config:
    #     src: "templates/vni-layer3.j2"
    #     confirm_commit: yes
    #     update: merge
    #     comment: Config Layer 3 VNIs
    - name: Config Layer 2 VNIs
      junipernetworks.junos.junos_config:
        src: "templates/vni-layer2.j2"
        confirm_commit: yes
        update: merge
        comment: Config Layer 2 VNIs