- name: Config Juniper MX-480 Setup
  hosts: mx-series
  gather_facts: no
  vars:
    ansible_command_timeout: 300
  vars_files:
    - vars/setup.yml
  tasks:
    - name: Juniper MX-480 setup (not automation needed in PoC)
      junipernetworks.junos.junos_config:
        src: "templates/setup-mx.j2"
        confirm_commit: yes
        update: merge
        comment: Juniper MX-480 setup

