- name: Config Juniper MX-480 VXLAN
  hosts: mx-series
  gather_facts: no
  vars:
    ansible_command_timeout: 300
  vars_files:
    - vars/setup.yml
    - vars/vni-vxlan.yml
  tasks:
    - name: Config Juniper MX-480 VXLAN
      junipernetworks.junos.junos_config:
        src: "templates/vni-vxlan-mx.j2"
        confirm_commit: yes
        update: merge
        comment: Config Layer 2/3 VNIs VXLAN

