- name: Delete Juniper MX-480
  hosts: mx-series
  gather_facts: no
  vars:
    ansible_command_timeout: 300
  vars_files:
    - vars/ebgp.yml
  tasks:
    - name: Delete eBGP Overlay
      junipernetworks.junos.junos_config:
        src: "templates/ebgp-overlay-delete.j2"
        confirm_commit: yes
        update: merge
        comment: Delete eBGP Overlay